name: My First Workflow

on:
  workflow_dispatch:
    inputs:
      Demo:
        default: "Some Default"
        required: true
  schedule:
    - cron: "* 1 * * *"
  push:
    branches: main

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Shell Demo
        run: echo "Hej flutter.com Devs 👋"
